from __future__ import annotations

import argparse

from train import run_training


DEFAULT_CONFIG = "configs/deepreg_synth.yaml"


def main():
    parser = argparse.ArgumentParser(
        description="Run the USRegistrator training pipeline."
    )
    parser.add_argument(
        "--config",
        type=str,
        default=DEFAULT_CONFIG,
        help=(
            "Optional config override. The recommended workflow is to edit "
            f"{DEFAULT_CONFIG} and run `python main.py`."
        ),
    )
    parser.add_argument(
        "--tutorial",
        type=str,
        default=None,
        help=(
            "Run a registered tutorial instead of --config. A tutorial builds its own "
            "config and resolves data paths for you. Use --list-tutorials to see them."
        ),
    )
    parser.add_argument(
        "--list-tutorials",
        action="store_true",
        help="List the available tutorials and exit.",
    )
    parser.add_argument(
        "--data-root",
        type=str,
        default=None,
        help="Tutorial data root; a dataset manifest is generated by scanning it.",
    )
    parser.add_argument(
        "--manifest",
        type=str,
        default=None,
        help="Tutorial dataset manifest to use instead of scanning --data-root.",
    )
    parser.add_argument("--epochs", type=int, default=None, help="Tutorial: override epochs.")
    parser.add_argument("--image-size", type=int, default=None, help="Tutorial: override cube edge.")
    parser.add_argument("--lr", type=float, default=None, help="Tutorial: override learning rate.")
    parser.add_argument(
        "--no-align",
        action="store_true",
        help=(
            "Tutorial: disable the shared-grid resample. Reproduces the misaligned "
            "baseline — useful for comparison, not for real runs."
        ),
    )
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Tutorial: report initial mask Dice and exit without training.",
    )
    args = parser.parse_args()

    if args.list_tutorials:
        from tutorials import describe_tutorials

        print("Available tutorials:")
        print(describe_tutorials())
        return

    if args.tutorial:
        from tutorials import run_tutorial

        run_tutorial(
            args.tutorial,
            data_root=args.data_root,
            manifest=args.manifest,
            epochs=args.epochs,
            image_size=args.image_size,
            lr=args.lr,
            align=False if args.no_align else None,
            check_only=args.check_only,
        )
        return

    run_training(args.config)


if __name__ == "__main__":
    main()
